### ISSUE TITLE
/tmp filling up

### ISSUE THREAD

**Issue by gleporeNARA** [tballison/commoncrawl-fetcher-lite#27]
Using lots of threads can result in /tmp filling up very quickly, which can be a bad thing on some systems. 20 threads filled 16GB /tmp in just a few minutes.

Perhaps a setting to configure a different /tmp location for the commoncrawl indexes?

On a related note, for multiple runs pulling different kinds of files from Common Crawl, it might make sense to store the indexes somewhere outside of /tmp so as not to re-download them every time.

**Comment by tballison** [comment]
I had been meaning to do this. The challenge was that there was a single fetcher for the index fetcher and the file extractor.  I've broken this out into the fetcher which pulls the literal bytes out of the WARC and the indexFetcher which grabs the index files.  This means that you can now read index files from your local file system but still extract from the WARCs via s3 or https.

I've documented how to do this in https://github.com/tballison/commoncrawl-fetcher-lite/blob/main/AdvancedScenarios.md

**Comment by gleporeNARA** [comment]
Outstanding! Thanks, I will recompile after my current run is done. This will also help me identify new formats to create signatures for in PRONOM.

**Comment by tballison** [comment]
https://github.com/tballison/commoncrawl-fetcher-lite/releases

**Comment by gleporeNARA** [comment]
Would it make sense to be able to limit the number of index files downloaded? 300GB is a lot of data. Perhaps a setting that works like maxFilesExtracted to limit index files, maxIndexFilesDownloaded.

That way a user could use the local index files for repeat extractions of files without pulling down the whole 300GB.

**Comment by gleporeNARA** [comment]
Also, in the event of a crash, does restarting the process skip already downloaded index files?

WARN  [pool-2-thread-12] 15:23:06,761 org.tallison.cc.index.io.BackoffHttpFetcher got backoff warning (#4) for https://data.commoncrawl.org/cc-index/collections/CC-MAIN-2023-06/indexes/cdx-00280.gz. Will sleep 1800 seconds. Message: bad status code: 503 :: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SlowDown</Code><Message>Please reduce your request rate.</Message><RequestId>4BN8B4E3MGZHXJ7P</RequestId><HostId>iV9YW4ma+StabztL8eBnfRuhvFhMithWHvv71OH8iPa3g6Z+vOLzHq1dvd+tSSaD236XSE5/UlJJdU4ZdCAH3w==</HostId></Error>. 
INFO  [pool-2-thread-7] 15:23:25,106 org.tallison.cc.index.extractor.CCIndexFetcher successfully downloaded: cc-index/collections/CC-MAIN-2023-06/indexes/cdx-00278.gz
INFO  [pool-2-thread-7] 15:23:25,179 org.tallison.cc.index.extractor.CCIndexFetcher Index fetcher finished
INFO  [pool-2-thread-19] 15:23:34,813 org.tallison.cc.index.extractor.CCIndexFetcher successfully downloaded: cc-index/collections/CC-MAIN-2023-06/indexes/cdx-00279.gz
INFO  [pool-2-thread-19] 15:23:34,887 org.tallison.cc.index.extractor.CCIndexFetcher Index fetcher finished
INFO  [pool-2-thread-14] 15:23:48,497 org.tallison.cc.index.extractor.CCIndexFetcher successfully downloaded: cc-index/collections/CC-MAIN-2023-06/indexes/cdx-00281.gz
INFO  [pool-2-thread-14] 15:23:48,575 org.tallison.cc.index.extractor.CCIndexFetcher Index fetcher finished
ERROR [main] 15:50:13,007 org.tallison.cc.index.extractor.CCIndexFetcher main loop exception
java.util.concurrent.ExecutionException: org.tallison.cc.index.io.ThrottleException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
        at org.tallison.cc.index.extractor.CCIndexFetcher.execute(CCIndexFetcher.java:85) [commoncrawl-fetcher-lite-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.tallison.cc.index.extractor.CCIndexFetcher.main(CCIndexFetcher.java:57) [commoncrawl-fetcher-lite-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.tallison.cc.index.extractor.CCFetcherCli.main(CCFetcherCli.java:34) [commoncrawl-fetcher-lite-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
Caused by: org.tallison.cc.index.io.ThrottleException
        at org.tallison.cc.index.io.BackoffHttpFetcher.fetchWithBackOff(BackoffHttpFetcher.java:103) ~[commoncrawl-fetcher-lite-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.tallison.cc.index.io.BackoffHttpFetcher.fetch(BackoffHttpFetcher.java:51) ~[commoncrawl-fetcher-lite-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.tallison.cc.index.extractor.CCIndexFetcher$IndexFetcher.fetch(CCIndexFetcher.java:135) ~[commoncrawl-fetcher-lite-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.tallison.cc.index.extractor.CCIndexFetcher$IndexFetcher.call(CCIndexFetcher.java:128) ~[commoncrawl-fetcher-lite-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.tallison.cc.index.extractor.CCIndexFetcher$IndexFetcher.call(CCIndexFetcher.java:102) ~[commoncrawl-fetcher-lite-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.tallison.cc.index.io.ThrottleException
        at org.tallison.cc.index.extractor.CCIndexFetcher.execute(CCIndexFetcher.java:92)
        at org.tallison.cc.index.extractor.CCIndexFetcher.main(CCIndexFetcher.java:57)
        at org.tallison.cc.index.extractor.CCFetcherCli.main(CCFetcherCli.java:34)
Caused by: java.util.concurrent.ExecutionException: org.tallison.cc.index.io.ThrottleException
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.tallison.cc.index.extractor.CCIndexFetcher.execute(CCIndexFetcher.java:85)
        ... 2 more
Caused by: org.tallison.cc.index.io.ThrottleException
        at org.tallison.cc.index.io.BackoffHttpFetcher.fetchWithBackOff(BackoffHttpFetcher.java:103)
        at org.tallison.cc.index.io.BackoffHttpFetcher.fetch(BackoffHttpFetcher.java:51)
        at org.tallison.cc.index.extractor.CCIndexFetcher$IndexFetcher.fetch(CCIndexFetcher.java:135)
        at org.tallison.cc.index.extractor.CCIndexFetcher$IndexFetcher.call(CCIndexFetcher.java:128)
        at org.tallison.cc.index.extractor.CCIndexFetcher$IndexFetcher.call(CCIndexFetcher.java:102)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
[1]+  Done                    clear
upstairs:/media/work/commoncrawl$
