### ISSUE TITLE
Won't download older crawls

### ISSUE THREAD

**Issue by gleporeNARA** [tballison/commoncrawl-fetcher-lite#30]
It appears that crawls older than CC-MAIN-2017-22 can't be downloaded. I tried several and all died with the same error, see below.

INFO  [pool-2-thread-4] 10:14:01,348 org.tallison.cc.index.extractor.CCFileExtractor Finished fetching 745,235,260 bytes in 88,630 ms for index gz: cc-index/collections/CC-MAIN-2017-04/indexes/cdx-00002.gz
ERROR [main] 10:14:01,451 org.tallison.cc.index.extractor.CCFileExtractor main loop exception
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
        at org.tallison.cc.index.extractor.CCFileExtractor.execute(CCFileExtractor.java:105) [commoncrawl-fetcher-lite-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.tallison.cc.index.extractor.CCFileExtractor.main(CCFileExtractor.java:69) [commoncrawl-fetcher-lite-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.tallison.cc.index.extractor.CCFetcherCli.main(CCFetcherCli.java:38) [commoncrawl-fetcher-lite-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
        at java.util.regex.Matcher.getTextLength(Matcher.java:1769) ~[?:?]
        at java.util.regex.Matcher.reset(Matcher.java:415) ~[?:?]
        at java.util.regex.Matcher.<init>(Matcher.java:252) ~[?:?]
        at java.util.regex.Pattern.matcher(Pattern.java:1149) ~[?:?]
        at org.tallison.cc.index.selector.RegexSelector.select(RegexSelector.java:38) ~[commoncrawl-fetcher-lite-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.tallison.cc.index.selector.RecordSelector.select(RecordSelector.java:61) ~[commoncrawl-fetcher-lite-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.tallison.cc.index.extractor.CCFileExtractorRecordProcessor.process(CCFileExtractorRecordProcessor.java:75) ~[commoncrawl-fetcher-lite-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.tallison.cc.index.extractor.CCFileExtractor$IndexWorker.processFile(CCFileExtractor.java:190) ~[commoncrawl-fetcher-lite-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.tallison.cc.index.extractor.CCFileExtractor$IndexWorker.call(CCFileExtractor.java:160) ~[commoncrawl-fetcher-lite-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.tallison.cc.index.extractor.CCFileExtractor$IndexWorker.call(CCFileExtractor.java:129) ~[commoncrawl-fetcher-lite-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
        at org.tallison.cc.index.extractor.CCFileExtractor.execute(CCFileExtractor.java:119)
        at org.tallison.cc.index.extractor.CCFileExtractor.main(CCFileExtractor.java:69)
        at org.tallison.cc.index.extractor.CCFetcherCli.main(CCFetcherCli.java:38)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.tallison.cc.index.extractor.CCFileExtractor.execute(CCFileExtractor.java:105)
        ... 2 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
        at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
        at java.base/java.util.regex.Matcher.reset(Matcher.java:415)
        at java.base/java.util.regex.Matcher.<init>(Matcher.java:252)
        at java.base/java.util.regex.Pattern.matcher(Pattern.java:1149)
        at org.tallison.cc.index.selector.RegexSelector.select(RegexSelector.java:38)
        at org.tallison.cc.index.selector.RecordSelector.select(RecordSelector.java:61)
        at org.tallison.cc.index.extractor.CCFileExtractorRecordProcessor.process(CCFileExtractorRecordProcessor.java:75)
        at org.tallison.cc.index.extractor.CCFileExtractor$IndexWorker.processFile(CCFileExtractor.java:190)
        at org.tallison.cc.index.extractor.CCFileExtractor$IndexWorker.call(CCFileExtractor.java:160)
        at org.tallison.cc.index.extractor.CCFileExtractor$IndexWorker.call(CCFileExtractor.java:129)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by tballison** [comment]
Not all fields were available in the earlier common-crawl runs.  I'm guessing the field that you're running the regex extractor against didn't exist?

**Comment by gleporeNARA** [comment]
Hmm, must be an error in the config file I'm using, using your recordSelector section still throws an error.

{
  "dryRun" : false,
  "extractTruncated": true,
  "indices": {
    "paths": [
      "crawl-data/CC-MAIN-2017-13/cc-index.paths.gz"
    ]
  },
  "numThreads": 1,
  "fetcher": {
    "throttleSeconds": [ 30, 30, 30]
  },
  "fetcher": {
    "profile": "xxxxxxx"
  },
  "recordSelector": {
    "should": {
      "mime_detected": [
        {
          "match": "application/octet-stream",
          "sample": 0.8
        }
      ]
    },
    "must": {
      "status": [
        {
          "match": "200"
        }
      ]
    }
  },
}

**Comment by gleporeNARA** [comment]
My original config:

```javascript
{
  "dryRun" : false,
  "extractTruncated": true,
  "indices": {
    "paths": [
      "crawl-data/CC-MAIN-2017-13/cc-index.paths.gz"
    ]
  },
  "numThreads": 1,
  "fetcher": {
    "throttleSeconds": [ 30, 30, 30]
  },
  "fetcher": {
    "profile": "glepore70"
  },
  "recordSelector": {
    "should": {
      "mime_detected": [
        {
          "match": "application/octet-stream",
          "sample": 0.8
        }
      ]
    },
    "must": {
      "status": [
        {
          "match": "200"
        }
      ]
    }
  },
}

```

**Comment by tballison** [comment]
I was pulling 2017-22 not 2017-13.  I wonder if `mime_detected` was added between those two?  I'll pull 2017-13 and take a look.

**Comment by gleporeNARA** [comment]
Yeah, that's it, no mime-detected in the older indexes. This from 2008-2009:

{"status":"200","url":"http://www.customs.gov.ag/","filename":"crawl-001/2008/11/29/24/1227988403310_24.arc.gz","length":"2081","mime":"text/html","offset":"61664986","digest":"GOCAYA7YHIUCOMDHWVSSJNGZSI7ILOXK"}

Just mime.

**Comment by tballison** [comment]
Should the behavior for a null value be a logged warning and a continuation of processing?

**Comment by tballison** [comment]
According to:
https://commoncrawl.org/2017/06/may-2017-crawl-archive-now-available/

mime_detected -- aka Tika detection -- came in in the CC-MAIN-2017-22 crawl.

**Comment by gleporeNARA** [comment]
Got it.

I've got enough octet-stream files analyzed from the most recent Crawls to reduce the number of files identified by Tika as octet-stream by roughly half. I thought it would be interesting to compare that to older Crawls, but that was before I knew Common Crawl was getting its mime-detected from Tika.

All good. I'll post to the Jira issue this week.

**Comment by tballison** [comment]
>For 2008-2009 there are only a few dozen octet-stream values in the entire index, which seems doubtful...

Y, you'd have to pull the bytes from every file in those crawls and run Tika (or your favorite file detection program) against those records.  ~waves hands about truncated records~
